### ISSUE TITLE
Label token is useless?

### ISSUE THREAD

**Issue by jameslahm** [HarborYuan/ovsam#10]
Thank you for your great work! I found the label token in OVSAMHead seems to be useless because the cls_embed is multiplied with 0 like below.  https://github.com/HarborYuan/ovsam/blob/62c8ab5ca6e4b3ea75a0ea8a0a806f0a19da9cc6/seg/models/heads/ovsam_head.py#L219

Do I understand right? Thank you!

**Comment by HarborYuan** [comment]
You are correct. 

Please refer to the CLIP2SAM section in the paper. The design with Q_label corresponds to the "straightforward" approach.
