### ISSUE TITLE
Does OV-SAM support segment anything mode?

### ISSUE THREAD

**Issue by whu-pzhang** [HarborYuan/ovsam#13]
Thanks for you excellent work! 

As a SAM variant, does OV-SAM support segment everything(with class) mode in SAM? 
Just like [`SamAutomaticMaskGenerator`](https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/automatic_mask_generator.py#L35C7-L35C32) in sam

**Comment by HarborYuan** [comment]
Hi @whu-pzhang ,

Thanks for your question.

Though our method is a SAM variant, we implement our method with the OpenMMLab ecosystem. Adapting it to the original SAM framework may need some engineering work, but it is possible.
