### ISSUE TITLE
text embedding

### ISSUE THREAD

**Issue by JIaqiYang78** [HarborYuan/ovsam#15]
Hello author,

I want to ask where is the text embedding extration file? How do you process the text dataset? Thanks!

**Comment by HarborYuan** [comment]
Hi @JIaqiYang78 ,

Thanks for your interest.

Please extract the text embedding following:
```
bash tools/dist.sh gen_cls seg/configs/ovsam/ovsam_coco_rn50x16_point.py 8
```
You can read the file `tools/gen_cls.py` for details.
