### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/.cache/embd/RN50x16_CocoOVDataset.pth'

### ISSUE THREAD

**Issue by WuHenry-0609** [HarborYuan/ovsam#16]
Hi, thank you for your hard work!
I run your code but it raises an error:
"FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/.cache/embd/RN50x16_CocoOVDataset.pth'"
Could you tell me how to solve this problem?
I'm looking forward to your reply.

**Comment by HarborYuan** [comment]
Hi @WuHenry-0609 ,

Thanks for your question.

Please extract the language embeddings first.
```
bash tools/dist.sh gen_cls seg/configs/ovsam/ovsam_coco_rn50x16_point.py 8
```

It will automatically generate the embeddings and put it into the `~/.cache/embd`
