### ISSUE TITLE
about "Feature-Crop baseline"

### ISSUE THREAD

**Issue by nhw649** [HarborYuan/ovsam#17]
Hello, I would like to ask how the "Feature-Crop baseline" mentioned in the paper crops features using a mask? Is there any specific paper that I can refer to?

**Comment by HarborYuan** [comment]
Hi @nhw649 ,

Thanks for your question.

As mentioned in the paper, the "feature-crop baseline" is quite simple. It first gets the object mask with SAM and then extracts the instance feature from the CLIP backbone with [`mask_pool`](https://github.com/HarborYuan/ovsam/blob/126ba2b6422f5bec8bb9fad271c4cda16efde5ee/seg/models/utils/mask_pool.py#L7).
