### ISSUE TITLE
Reduce Train Batch Size

### ISSUE THREAD

**Issue by WuHenry-0609** [HarborYuan/ovsam#19]
**Hi! I want to reduce train batch size from 2 to 1. How can I do it?
I'm looking forward to your early reply. Thanks!**

**Comment by HarborYuan** [comment]
Hi @WuHenry-0609 ,

You can change the batchsize on each GPU from `2` to `1` ([here](https://github.com/HarborYuan/ovsam/blob/126ba2b6422f5bec8bb9fad271c4cda16efde5ee/seg/configs/_base_/datasets/sam_img.py#L40)).
