### ISSUE TITLE
Can not open online demo

### ISSUE THREAD

**Issue by BboyHanat** [HarborYuan/ovsam#20]
seem like model sha256 doesn't match?

**Comment by HarborYuan** [comment]
Hi @BboyHanat ,

Thanks for your reporting.
The sha256 issue is caused by occasional network errors, and I have restarted the hugging face space. You can use it now.

**Comment by HarborYuan** [comment]
You can also try the demo on [`OpenXLab`](https://openxlab.org.cn/apps/detail/houshaowei/Open-Vocabulary_SAM).

**Comment by nullkatar** [comment]
Hey @HarborYuan thanks a lot for your work! But can I gently ask you to restart huggingface hub instance again? Also OpenXLab didnt work for me smh, it was just not outputting anything,

**Comment by HarborYuan** [comment]
Hi @nullkatar ,

Thanks for your information.

I have checked and found that it is due to Gradio's API change. I have fixed the bug. Please let me know if there are any other problems with the online demo.

**Comment by nullkatar** [comment]
Hi @HarborYuan! 

Thanks a lot for quick response! Both of the demos are online, but not showing any output unfortunately :(
![image](https://github.com/HarborYuan/ovsam/assets/27498544/3e68cef3-4670-475a-b482-d447f67494fb)

**Comment by HarborYuan** [comment]
Hi @nullkatar ,

I just have a try, and it works well. Could you please click more times to figure out whether it works well? You can also download the demo to run in your own GPU to inference.

**Comment by nullkatar** [comment]
I putting more points and discovered that it was a browser issue... I'm terribly sorry and once again thanks a lot @HarborYuan  for quick response!!
