### ISSUE TITLE
How to add prompt?

### ISSUE THREAD

**Issue by hahapt** [HarborYuan/ovsam#22]
I try the demo in huggingface, but it only support to click some place in picture to do inference, can it support add some text prompt instead of click on picture?

**Comment by HarborYuan** [comment]
Hi @hahapt ,

In Open-Vocabulary SAM, we support the use of bounding boxes and points as prompts. Currently, we do not support text prompts.

Thanks for your question.

**Comment by HarborYuan** [comment]
I want to close the issue first. Feel free to re-open or raise a new one if you have any further questions.
