### ISSUE TITLE
Got a problem when adding "--show" and "--show-dir" when running test.py

### ISSUE THREAD

**Issue by MW-ZHOU** [HarborYuan/ovsam#23]
Hi,

I got this error when I add `--show` and `--show-dir` as script parameters. Have you encountered this problem before? Can you please help me?`AttributeError: 'InstanceData' object has no attribute 'scores'`

<img width="1439" alt="image" src="https://github.com/HarborYuan/ovsam/assets/41655056/3669fb4a-b46e-482d-8c8f-156798d48035">

the version for mmcv, mmdet and other packages are listed as below.
<img width="506" alt="image" src="https://github.com/HarborYuan/ovsam/assets/41655056/6e89acc4-2231-4bfc-89fc-07aaa5cbe623">

**Comment by HarborYuan** [comment]
Hi @MW-ZHOU ,

Thanks for your interest in our work.

We did not add support for the visualization. If you want to visualize the results of ovsam, please re-implement [visualizer](https://github.com/open-mmlab/mmdetection/blob/cfd5d3a985b0249de009b67d04f37263e11cdf3d/mmdet/visualization/local_visualizer.py#L25) in mmdet, and add the re-implemented visualizer in the [config](https://github.com/HarborYuan/ovsam/blob/126ba2b6422f5bec8bb9fad271c4cda16efde5ee/seg/configs/_base_/default_runtime.py#L27).

Please let me know if you have any other question.

**Comment by MW-ZHOU** [comment]
I see, thanks for your reply.
