### ISSUE TITLE
Does it support full segmentation like SAM?

### ISSUE THREAD

**Issue by Atumyugi** [HarborYuan/ovsam#24]
Thank you very much for your work, can it work like the SAM full segmentation process?

**Comment by HarborYuan** [comment]
Hi @Atumyugi ,

Thanks for your question.

Open-Vocabulary SAM follows the setting of the Segment Anything Model and requires the prompt for segmentation during inference. To support the full segmentation, e.g., instance segmentation, you need to add an extra proposal network to generate the object bounding boxes first.

**Comment by HarborYuan** [comment]
Hi @Atumyugi ,

I would like to close the issue first. If you have any further questions, feel free to re-open the issue or raise a new one.
