### ISSUE TITLE
How to use demo offline?

### ISSUE THREAD

**Issue by yepengxj** [HarborYuan/ovsam#25]
How to use demo offline?

**Comment by HarborYuan** [comment]
Hi @yepengxj ,

Thanks for your question. Please refer to the `2` in the [Usage](https://github.com/HarborYuan/ovsam?tab=readme-ov-file#usage).

Please let me know if you have any problems when using the scripts.

**Comment by HarborYuan** [comment]
Hi @yepengxj ,

I would like to close the issue first. If you have any further questions, feel free to re-open the issue or raise a new one.

**Comment by HarborYuan** [comment]
Hi @yepengxj ,

I would like to close the issue first. If you have any further questions, feel free to re-open the issue or raise a new one.
