### ISSUE TITLE
Problem regarding to creating the environment

### ISSUE THREAD

**Issue by EricLabile** [HarborYuan/ovsam#26]
After conda install pytorch torchvision torchaudio cuda-toolkit pytorch-cuda==12.1 -c pytorch -c "nvidia/label/cuda-12.1.0", there will be an error like:

Could not solve for environment specs
The following package could not be installed
└─ pytorch-cuda 12.1  is not installable because it requires
   └─ libnvjitlink >=12.1.105,<12.2.0 , which does not exist (perhaps a missing channel).

Can you help me with this? Thank you so much.

**Comment by HarborYuan** [comment]
HI @EricLabile ,

This may be due to some changes in the conda server. You may try different CUDA and Pytorch versions. But please keep in mind that the mmcv and mmdet versions are better fixed as in the README.

**Comment by EricLabile** [comment]
> HI @EricLabile ,
> 
> This may be due to some changes in the conda server. You may try different CUDA and Pytorch versions. But please keep in mind that the mmcv and mmdet versions are better fixed as in the README.

Thank you for your prompt reply. Could you please provide a minimum version of Pytorch and CUDA for me to try?

**Comment by HarborYuan** [comment]
I think it would be better to use Pytoch >= 2.0 and CUDA >= 11.6. Using pip to install pytorch is also a good option.

**Comment by EricLabile** [comment]
> I think it would be better to use Pytoch >= 2.0 and CUDA >= 11.6. Using pip to install pytorch is also a good option.

Thank you. I will try it and update if successful.

**Comment by EricLabile** [comment]
Pytorch 2.3.1 and cuda 11.8 works well.
To be specific, use:
conda create --name ovseg python=3.10
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
conda install -c "nvidia/label/cuda-11.8.0" cuda-nvcc
conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit
and follow the README.md afterwards.

**Comment by HarborYuan** [comment]
@EricLabile Thanks for your report.

**Comment by HarborYuan** [comment]
Hi @EricLabile ,

There is an alternative option to install pytorch with conda:
```
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 cuda -c pytorch  -c "nvidia/label/cuda-12.1.0" -c "nvidia/label/cuda-12.1.1"
```

You can have a try.

**Comment by zxx0809** [comment]
Excuse m. What are your mvcc versions? I also have environmental problems, thank you

**Comment by HarborYuan** [comment]
Hi @zxx0809 ,

You can raise your questions in the your opened issue.

Thank you.
