### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by Danbinabo** [HarborYuan/ovsam#27]
I prepare envirement and want to Inference,but run bash tools/dist.sh test seg/configs/ovsam/ovsam_coco_rn50x16_point.py 8 happend GRT false,
 its:  File "/mnt/NewDataShare/D4/common/wbzhou/MLLM/ovsam/seg/models/data_preprocessor/ovsam_preprocessor.py", line 193, in forward
    gt_instances.point_coords = get_center_coords(
  File "/mnt/NewDataShare/D4/common/wbzhou/MLLM/ovsam/seg/models/data_preprocessor/ovsam_preprocessor.py", line 24, in 
![ovsam_bug](https://github.com/HarborYuan/ovsam/assets/43404822/ba15c437-cad2-4975-b64f-f9e77e08c0b7)

Is this issue due to incorrect environment configuration?
torch==2.1.2+cu121  torchvison==0.16.2+cu121 mmcv==2.1.0 mmdet==3.3.0

**Comment by HarborYuan** [comment]
Hi @Danbinabo ,

I have a brief check of your screenshot. It is not expected to have the shown error with your current versions. The error seems like there is no suitable compiled CUDA op. I suspect that it is because of the way you install your env.

Please give more descriptions of how you install the environment if possible.

**Comment by Danbinabo** [comment]
Inference: tools/dist.sh test seg/configs/ovsam/ovsam_coco_rn50x16_point.py 8 result:  
![image](https://github.com/HarborYuan/ovsam/assets/43404822/22a771c6-39ce-4c64-85d0-d658b2ed7ba6)
 this default is test cocodatasets, I want to inference other segmentation data(img, png-segmentation label), deal data as sam data 
![image](https://github.com/HarborYuan/ovsam/assets/43404822/79113e04-4021-4f52-b5d3-50a9afd77458)
then i should how to test? i not found change config --data,Could you give me some details

**Comment by HarborYuan** [comment]
You need to modify [this](https://github.com/HarborYuan/ovsam/blob/1d4dfb287fe113e8ecd60f76b4385c5506f566ca/seg/configs/ovsam/ovsam_coco_rn50x16_point.py#L13) ([file](https://github.com/HarborYuan/ovsam/blob/1d4dfb287fe113e8ecd60f76b4385c5506f566ca/seg/configs/_base_/datasets/coco_ov_instance_lsj.py)) config file to support more dataset.

To write such a config, you may need to write a new dataset class starting from [COCO](https://github.com/HarborYuan/ovsam/blob/1d4dfb287fe113e8ecd60f76b4385c5506f566ca/seg/datasets/coco_ins_ov.py#L48) and import it to your config.

**Comment by HarborYuan** [comment]
BTW, could you please provide some details about how you fix the env bug? It would be great for other guys to run the code.
