### ISSUE TITLE
Missing ovsam.py File - Upload Inquiry

### ISSUE THREAD

**Issue by CVHub520** [HarborYuan/ovsam#3]
Hello,

I encountered a ModuleNotFoundError related to the absence of the ovsam.py file. Could you please confirm if it will be uploaded?

Error Details:

```
ModuleNotFoundError: Failed to import seg.models.detectors in seg/configs/ovsam/ovsam_coco_rn50x16_point.py, line 7 for No module named 'seg.models.detectors.ovsam'
```

Thank you!

**Comment by CVHub520** [comment]
Additionally, I am interested in obtaining ONNX export settings and a minimal example for running inference based on ONNX Runtime (ORT). Could you provide guidance or share a minimal running example?

**Comment by HarborYuan** [comment]
Hi @CVHub520 ,

Thanks for your interest in our work. Could you please help me provide the script that you are using to run the model?

**Comment by HarborYuan** [comment]
> Additionally, I am interested in obtaining ONNX export settings and a minimal example for running inference based on ONNX Runtime (ORT). Could you provide guidance or share a minimal running example?

I am not very familiar with onnx export. But this project is highly integrated with mmdet. I am not sure whether they provide the tools for exporting the onnx.

**Comment by HarborYuan** [comment]
Hi @CVHub520 ,

I fixed this bug. It was caused by the `.gitignore` file. Thanks for reporting.

**Comment by CVHub520** [comment]
It work; thank you very much.
