### ISSUE TITLE
Where can I get the sam dataset

### ISSUE THREAD

**Issue by zxx0809** [HarborYuan/ovsam#31]
I downloaded the SA-1B dataset, but the website says NOTE: There are no class labels for the images or mask annotations.
After downloading and decompressing, it is not a json file. Where can I download the SAM dataset of your project

**Comment by HarborYuan** [comment]
Hi @zxx0809 ,

Thanks for your interest in our work.

I do not understand your question. Our ovsam uses the original SA-1B dataset for the sam2clip training, and we do not use any label for SA-1B dataset.

**Comment by zxx0809** [comment]
Thank you for your prompt response. The issue has been resolved. Thank you!

**Comment by 1523900304** [comment]
Hello, I unzipped the sam1b dataset, but there is only one file in it, and nothing else. and FileNotFoundError: [Errno 2] No such file or directory: 'data/sam/val.txt'

**Comment by HarborYuan** [comment]
Hi @1523900304 ,

You are expected to create your val.txt. Please refer to the README for the format.

**Comment by zxx0809** [comment]
> Hello, I unzipped the sam1b dataset, but there is only one file in it, and nothing else. and FileNotFoundError: [Errno 2] No such file or directory: 'data/sam/val.txt'您好，我解压缩了 sam1b 数据集，但其中只有一个文件，没有其他文件。和 FileNotFoundError： [Errno 2] 没有这样的文件或目录： 'data/sam/val.txt'

把你下载的数据集压缩包后缀名从.tar改成.tar.gz再解压缩就可以了

**Comment by 1523900304** [comment]
@zxx0809 thank you, this issue has been resolved

**Comment by 1523900304** [comment]
@HarborYuan i run bash tools/dist.sh train seg/configs/sam2clip/sam2clip_vith_rn50x16.py 1, but error 
File "/mnt/auto-labeling/shenguoxin2/ovsam-main/seg/datasets/pipeliens/loading.py", line 368, in transform
    assert mmengine.exists(feat_path)
AssertionError
then i print the feat_path, data/sam_feat/sa_xxxxx_vit_h_cache.pth, but the dir sam_feat is not exist
the class init as follows:
class LoadFeatFromFile(BaseTransform):
    def __init__(self, model_name='vit_h', data_dir='data/sam_feat', force_load=True):

**Comment by 1523900304** [comment]
@HarborYuan thanks,it has been resolved
