### ISSUE TITLE
Segmentation Problems with Multiple Objects of the Same Kind

### ISSUE THREAD

**Issue by Minsky520** [HarborYuan/ovsam#33]
Hi, I want to know if I want to segment out class A objects. If there is more than one class A object in the image, then by entering the class A name, will all the objects be segmented out.
Looking forward to your reply

**Comment by HarborYuan** [comment]
Hi @Minsky520 ,

Thanks for your question. In ovsam, you can enter prompts like points and bounding boxes. We currently do not support text as prompts. I think your description is similar to the Referring Expression Segmentation task.

**Comment by Minsky520** [comment]
Thanks for your reply, I've basically figured out your findings, and thanks for the advice!
