### ISSUE TITLE
How can I evaluate on LVIS dataset?

### ISSUE THREAD

**Issue by Dyb3438** [HarborYuan/ovsam#34]
Thanks for your sharing of your excellent work! 

As described in the title, can you provide some guidance for me to validate OVSAM on LVIS dataset.

**Comment by lxtGH** [comment]
@HarborYuan Please help him with test scripts on LVIS dataset.

**Comment by HarborYuan** [comment]
Hi @Dyb3438 ,

Thanks for your interest. I will upload the code for LVIS testing in the next few days. Please stay tuned.

**Comment by Dyb3438** [comment]
Hi @HarborYuan,

Can I know when I can see the test scripts on LVIS dataset? Five days had flown by since you replied last time, and 3 weeks had flown by since this issue was created.

Hope for your updates!
