### ISSUE TITLE
Prompt compare SAM

### ISSUE THREAD

**Issue by Danbinabo** [HarborYuan/ovsam#35]
OVSAM prompt is point and box,Is it any different compare with SAM? in train or infer, hao to get prompt? if test on images, mast get prompt by det or assign a bbox or rect?Can you make predictions by generating dense boxes

**Comment by lxtGH** [comment]
1, We follow the same prompt encoder design as the SAM. 

2, When training or testing using prompt, we directly load the ground truth boxes (gt center points) or detector boxes as visual prompt to get the corresponding mask and label. Check the code here. 

https://github.com/HarborYuan/ovsam/blob/33e6eb133c66f21ff325e11bdce101c3ea1b74ec/seg/models/data_preprocessor/ovsam_preprocessor.py#L55

3, Dense boxes can also be support by put all boxes as prompts and only runs the ov-sam decoder multiple times.
