### ISSUE TITLE
huggingface space failed

### ISSUE THREAD

**Issue by tanshuai0219** [HarborYuan/ovsam#36]
Hey, the huggingface space fails to work.

**Comment by HarborYuan** [comment]
Hi @tanshuai0219 ,

Thanks for your reporting. I have restarted the demo on HuggingFace. 

A message for the future HuggingFace demo-related problem: 
Please directly send an email to me. I will try to fix it ASAP. If you want to try ovsam immediately, you can also refer to README to deploy the ovsam demo locally, which can be done quickly with just a few commands.

```
git lfs install
git clone https://huggingface.co/spaces/HarborYuan/ovsam ovsam_demo
cd ovsam_demo
conda create -n ovsam_demo python=3.10  && conda activate ovsam_demo
python -m pip install gradio==4.7.1
python -m pip install -r requirements.txt
python main.py
```
