### ISSUE TITLE
Evaluation scripts on LVIS dataset

### ISSUE THREAD

**Issue by Dyb3438** [HarborYuan/ovsam#38]
Hi @HarborYuan,

Can I know when I can see the test scripts on LVIS dataset? Five days had flown by since you replied last time, and 3 weeks had flown by since this issue was created.

Hope for your updates!

_Originally posted by @Dyb3438 in https://github.com/HarborYuan/ovsam/issues/34#issuecomment-2257345897_

**Comment by HarborYuan** [comment]
Hi @Dyb3438 ,

Thanks for your reminder. I have uploaded LVIS-related code and models.
