### ISSUE TITLE
how to inference on my custom data?

### ISSUE THREAD

**Issue by MargeryLab** [HarborYuan/ovsam#43]
i want to test the inference results on my data,  how to modify the code or config?

**Comment by HarborYuan** [comment]
Hi @MargeryLab ,

Thanks for your interest.

For your own dataset, I think the easiest way is to reuse the dataloader of SA-1b. Please refer to [here](https://github.com/HarborYuan/ovsam/blob/main/seg/configs/_base_/datasets/sam.py). 

If you want to test one or two samples, I recommend you use the Gradio demo. Please refer to the section 2 of the Usage in the README ([here](https://github.com/HarborYuan/ovsam?tab=readme-ov-file#usage)).
