### ISSUE TITLE
About SAM datasets

### ISSUE THREAD

**Issue by jiugexuan** [HarborYuan/ovsam#44]
In SAM datasets:
```
├── sam
│   ├── train.txt
│   ├── val.txt
│   ├── sa_000020
│   │   ├── sa_223750.jpg
│   │   ├── sa_223750.json
│   │   ├── ...
│   ├── ...
```
how can i get the `train.txt` & `val.txt`?

**Comment by HarborYuan** [comment]
Hi @jiugexuan ,

You can write the folder names in the train.txt and val.txt. There are 1000 folders in the SA-1B dataset, so 1% of the SA-1B dataset corresponds to 10 folders.
