### ISSUE TITLE
Hugging Face Space link is invalid.

### ISSUE THREAD

**Issue by UQHTy** [HarborYuan/ovsam#47]
Hi, brilliant work. Hugging Face LINK is invalid.

**Comment by HarborYuan** [comment]
Hi @UQHTy ,

Thanks for reporting this issue. I also cannot access the huggingface space now. It seems like a temporal internal error of huggingface.

I recommend you try this Huggingface demo locally. (Please refer to the README)

**Comment by UQHTy** [comment]
@HarborYuan  Thanks for your reply. However, I need to download several weights (including, ovsam_R50x16_lvisnorare.pth; R50x16_fpn_lvis_norare_v3det.pth; RN50x16_LVISV1Dataset.pth; sam2clip_vith_rn50.pth) to run the ovsam_demo.
Could you please provide the links to the relevant weights?  Many thanks

**Comment by HarborYuan** [comment]
For class embeddings, you need to generate them in your machine. (Please refer to `gen_cls` in README).

For model weights, they are already provided. (https://huggingface.co/HarborYuan/ovsam_models).

I recommend you read the README file carefully before running the project.

**Comment by HarborYuan** [comment]
The Huggingface demo has been recovered.
