### ISSUE TITLE
Release Timeline for RWKV-SAM Pretrained Model

### ISSUE THREAD

**Issue by Yaziwel** [HarborYuan/ovsam#48]
Hi, I'm very interested in leveraging the RWKV-SAM model to support my research. Could you kindly provide any updates regarding the expected release timeline for the pretrained model weights?

**Comment by HarborYuan** [comment]
Hi @Yaziwel ,

Thanks for your interest. We are currently working on some other projects. We may release more model weights and code early next year. Please stay tuned.
