### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by CVHub520** [HarborYuan/ovsam#5]
Hi, could you please provide the download link for `RN50x16_CocoOVDataset.pth`? I couldn't find the relevant download link.

**Comment by HarborYuan** [comment]
You may generate it by yourself:
```
bash tools/dist.sh gen_cls seg/configs/ovsam/ovsam_coco_rn50x16_point.py 8
```

Please also refer to the details here:
> https://github.com/HarborYuan/ovsam#-training

**Comment by CVHub520** [comment]
Resolved, thanks for the response. 

BTW, could u please provide an inference demo if possible? Currently, it seems that only training and testing code is provided.

**Comment by HarborYuan** [comment]
> Resolved, thanks for the response.
> 
> BTW, could u please provide an inference demo if possible? Currently, it seems that only training and testing code is provided.

Please refer to the second item of the `Usage` in README.md

**Comment by CVHub520** [comment]
Thank you for your feedback. Currently, I can use gradio for inference, as you mentioned. 

However, while I attempted to convert the model using `torch.onnx.export`, the resulting ONNX file was always empty. Additionally, a series of seemingly random numbers were continuously printed.

```bash
(1,384,.,.) = 
 0.001 *
  7.4430
...
(255,384,.,.) = 
 0.01 *
  1.6353

(256,384,.,.) = 
 0.01 *
  2.2419
[ torch.FloatTensor{256,384,1,1} ]
```

**Comment by HarborYuan** [comment]
Hi @CVHub520 ,

I don’t have much experience in model deployment. Could you please have a try on [MMDepoly](https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet.html#mmdetection-deployment)? I guess they provide some tools to deploy models in the OpenMMLab ecosystem.

Please let me know if you have any other question.

**Comment by haoyi-duan** [comment]
Hi, @CVHub520, any update on the inference model deployment?
