### ISSUE TITLE
Huggingface online demo does not work

### ISSUE THREAD

**Issue by burningsoulll** [HarborYuan/ovsam#52]
https://huggingface.co/spaces/HarborYuan/ovsam
![image](https://github.com/user-attachments/assets/1d8a415b-901e-4d3e-8c40-06e31fd3db31)

**Comment by HarborYuan** [comment]
Hi @burningsoulll ,

Thanks for your report. It works now. Also, you can try to download the huggingface code to run on your machine.

**Comment by xjwu1024** [comment]
> Hi [@burningsoulll](https://github.com/burningsoulll) ,
> 
> Thanks for your report. It works now. Also, you can try to download the huggingface code to run on your machine.

It seems not work again......

**Comment by HarborYuan** [comment]
It works now.

**Comment by xjwu1024** [comment]
> It works now.

cool！
