### ISSUE TITLE
 did anyone ever attach this to a language model?like mobilebert , use it to exactly segment the item we describe ,output the mask

### ISSUE THREAD

**Issue by arlisgreat** [HarborYuan/ovsam#53]

**Comment by HarborYuan** [comment]
Hi @arlisgreat ,

I am not sure whether I understand your question. It seems like your mentioned task is similar to Referring Expression Segmentation. Here is a related paper:

> LISA: Reasoning Segmentation via Large Language Model

Hope this can help.
