### ISSUE TITLE
Support for Automatic Mask Generation Without Prompts?

### ISSUE THREAD

**Issue by resecube** [HarborYuan/ovsam#54]
Hi,  thank you for your amazing work on this project! It has been incredibly helpful and inspiring.
I have a question: does the project support automatic mask generation, by which I mean segmenting an image without any prompts (similar to SAM)? If so, could you please share some guidance or examples on how to achieve this?    
Thanks again for your inspiring work!

**Comment by HarborYuan** [comment]
Hi @resecube ,

For ovsam, we use a similar promptable-based approach. That means it should be possible to use a similar pipeline as AutoMaskGeneration in SAM. But we have not tried before.

You can also try to use a detector to detect the objects first and then use ovsam for segmentation and labeling.

Hope this can help.

**Comment by resecube** [comment]
Thank you very much! I will try it!
