### ISSUE TITLE
segmentation for sky is error

### ISSUE THREAD

**Issue by chaoer** [HarborYuan/ovsam#6]
I tried both point and box prompt for [sample images](https://huggingface.co/spaces/HarborYuan/ovsam/tree/main/app/assets), but both failed for sky segmentation. 

I deploy the demo following the [instruments](https://github.com/HarborYuan/ovsam/blob/62c8ab5ca6e4b3ea75a0ea8a0a806f0a19da9cc6/README.md?plain=1#L24C11-L24C11). 
Is there anything i missed?

**Comment by HarborYuan** [comment]
Hi @chaoer ,

Thanks for your interest in our work.

You can try whether the segmentation of foreground objects works well. For background areas, due to the lack of data during training, it may not work well.

**Comment by chaoer** [comment]
thanks for your quick reply.

btw, the performance on foreground objects is awesome.
