### ISSUE TITLE
Something wrong with the Ilustration?

### ISSUE THREAD

**Issue by ArsenLuca** [HarborYuan/ovsam#7]
![image](https://github.com/HarborYuan/ovsam/assets/23271554/23915494-374c-4ffe-b2d8-9f3134cbf331)
It seems like to be like this?

**Comment by HarborYuan** [comment]
Hi @ArsenLuca ,

Thanks for your interest in our work.

The direction of this arrow is based on how you understand the arrow. The technical details of the SAM2CLIP module follow the upper right part of this figure (figure 3 in the paper). SAM Encoder, CLIP Encoder, and a neck are needed in the SAM2CLIP process for distillation. The arrow here mainly describes the knowledge transfer direction (from SAM encoder to CLIP encoder + neck) during training. During the inference, the SAM Encoder is no longer needed.

I hope this can help you.

**Comment by ArsenLuca** [comment]
> Hi @ArsenLuca ,
> 
> Thanks for your interest in our work.
> 
> The direction of this arrow is based on how you understand the arrow. The technical details of the SAM2CLIP module follow the upper right part of this figure (figure 3 in the paper). SAM Encoder, CLIP Encoder, and a neck are needed in the SAM2CLIP process for distillation. The arrow here mainly describes the knowledge transfer direction (from SAM encoder to CLIP encoder + neck) during training. During the inference, the SAM Encoder is no longer needed.
> 
> I hope this can help you.

Got it , thanks
